[package]
name = "terradventure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
rand = "0.8.5"
bevy_rapier2d = "0.23.0"
serde = "1.0.195"
serde_json = "1.0.111"
rapier2d = "0.18.0"
bevy_ecs_tilemap = "0.11.0"
