[package]
name = "tiled_collider_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_rapier_collider_gen = "0.3.1"
image = "0.24.8"
